print(True)
print(False)
print('petik tunggal')
print("petik ganda")
print(88)
print(2.3)
print([1,2,3,4,6,8])
print(['satu','dua','tiga','sepuluh'])
print ((1,2,4,6,8))
print(("satu","dua","lima"))
print({"nama": "Mona","umur":18})
biodata = {"nama": "Mona", "umur":18}
print(biodata)
print(type(biodata))
